export GSETTINGS_SCHEMA_DIR_CONDA_BACKUP="${GSETTINGS_SCHEMA_DIR:-}"
export GSETTINGS_SCHEMA_DIR="$CONDA_PREFIX/share/glib-2.0/schemas"
export GI_TYPELIB_PATH_CONDA_BACKUP="${GI_TYPELIB_PATH:-}"
export GI_TYPELIB_PATH="$CONDA_PREFIX/lib/girepository-1.0"
