export GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=${GSETTINGS_SCHEMA_DIR:-}
export GSETTINGS_SCHEMA_DIR=$CONDA_PREFIX/share/glib-2.0/schemas

export GIO_MODULE_DIR_CONDA_BACKUP=${GIO_MODULE_DIR:-}
export GIO_MODULE_DIR=$CONDA_PREFIX/lib/gio/modules
