export GSETTINGS_SCHEMA_DIR=${GSETTINGS_SCHEMA_DIR_CONDA_BACKUP:-}
unset GSETTINGS_SCHEMA_DIR_CONDA_BACKUP
if [ -z $GSETTINGS_SCHEMA_DIR ]; then
    unset GSETTINGS_SCHEMA_DIR
fi
export GI_TYPELIB_PATH=${GI_TYPELIB_PATH_CONDA_BACKUP:-}
unset GI_TYPELIB_PATH_CONDA_BACKUP
if [ -z $GI_TYPELIB_PATH ]; then
    unset GI_TYPELIB_PATH
fi

