{% set major_minor = "2.51" %}
{% set version = major_minor + ".4" %}
{% set sha256 = "7c4247dfb2e8d5b596018f00ea8c05e76077a3f0bfcc07dda4492708f552c23e" %}

package:
  name: glib
  version: {{ version }}

source:
  fn: glib-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/glib/{{ major_minor }}/glib-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    # Related to this patch https://bugzilla.gnome.org/show_bug.cgi?id=673135
    # However, it was rejected by upstream. Homebrew decided to keep their own
    # copy ( https://raw.githubusercontent.com/Homebrew/patches/59e4d32/glib/hardcoded-paths.diff ).
    # We are essentially using that copy, but with some tweaks. Info at the link below.
    #
    # https://github.com/Homebrew/legacy-homebrew/blob/21ce7a56cb3fc40fe93d731cc654c69268796772/Library/Formula/glib.rb#L33-L39
    #
    - hardcoded-paths.patch

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python
    - pkg-config
    - libffi >=3.0.0
    - gettext
    - zlib 1.2.*
    - pcre
    - libiconv
  run:
    - libffi >=3.0.0
    - gettext
    - zlib 1.2.*
    - pcre
    - libiconv

test:
  commands:
    - test -f ${PREFIX}/lib/libglib-2.0.so  # [linux]
    - test -f ${PREFIX}/lib/libglib-2.0.dylib  # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://developer.gnome.org/glib/
  license: LGPL-2.1
  summary: 'Provides core application building blocks for libraries and applications written in C.'

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - scopatz
    - ocefpaf
    - pkgw
