{% set major_minor = "2.48" %}
{% set version = major_minor + ".0" %}
{% set sha256 = "744be6931ca914c68af98dc38ff6b0cf8381d65e335060faddfbf04c17147c34" %}

package:
  name: glib
  version: {{ version }}

source:
  fn: glib-{{ version }}.tar.xz
  url: http://ftp.acc.umu.se/pub/GNOME/sources/glib/{{ major_minor }}/glib-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    # Related to this patch https://bugzilla.gnome.org/show_bug.cgi?id=673135
    # However, it was rejected by upstream. Homebrew decided to keep their own
    # copy ( https://raw.githubusercontent.com/Homebrew/patches/59e4d32/glib/hardcoded-paths.diff ).
    # We are essentially using that copy, but with some tweaks. Info at the link below.
    #
    # https://github.com/Homebrew/legacy-homebrew/blob/21ce7a56cb3fc40fe93d731cc654c69268796772/Library/Formula/glib.rb#L33-L39
    #
    - hardcoded-paths.patch
    # patches forked from https://github.com/pkgw/conda-recipes
    #  Copyright 2014-2015 Peter Williams and collaborators.
    # This file is licensed under a 3-clause BSD license.
    - no-cocoa-notification.patch  # [osx]

build:
  number: 4
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python
    - xz 5.0.*
    - pkg-config
    - libffi  >=3.0.0
    - gettext
    - zlib 1.2.*
    - pcre
    - libiconv
  run:
    - libffi  >=3.0.0
    - gettext
    - zlib 1.2.*
    - pcre
    - libiconv

test:
  commands:
    - test -f ${PREFIX}/lib/libglib-2.0.so  # [linux]
    - test -f ${PREFIX}/lib/libglib-2.0.dylib  # [osx]

about:
  home: https://developer.gnome.org/glib/
  license: GNU Lesser General Public License v2.1
  summary: "Provides core application building blocks for libraries and applications written in C."

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - scopatz
